- hosts: production
  user: him2497
  become: true
  tasks:
    - action: ping
    - name: Install apache 2
      raw: sudo apt-get -y install apache2
    - name: Start Apache Server
      raw: sudo service apache2 restart
    - name: Copy files to remote host
      copy:
        src: dist/
        dest: /var/www/html
        mode: 0755
  vars_files:
    - vars/main.yml